"""user

Revision ID: 344ca20da8fb
Revises: 0ed2d4bad184
Create Date: 2022-07-01 12:40:32.659380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344ca20da8fb'
down_revision = '0ed2d4bad184'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
