"""user

Revision ID: 3ae3be77b928
Revises: ac2189ced8ee
Create Date: 2022-07-01 10:12:50.726538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae3be77b928'
down_revision = 'ac2189ced8ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
