"""image

Revision ID: 74931980e505
Revises: bbbefcf56ad2
Create Date: 2022-06-29 10:57:31.289411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74931980e505'
down_revision = 'bbbefcf56ad2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
