"""image

Revision ID: 75383c9bbfe6
Revises: 7ed051e66f96
Create Date: 2022-07-01 02:19:20.203995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75383c9bbfe6'
down_revision = '7ed051e66f96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pins', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
