"""image

Revision ID: 7ed051e66f96
Revises: e22fda1e5d05
Create Date: 2022-06-30 13:11:35.111802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed051e66f96'
down_revision = 'e22fda1e5d05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
