"""text

Revision ID: 93f4f65b427e
Revises: 75383c9bbfe6
Create Date: 2022-07-01 02:27:28.291904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f4f65b427e'
down_revision = '75383c9bbfe6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('text', sa.Text(), nullable=True))
    op.drop_index('ix_pins_description', table_name='pins')
    op.create_index(op.f('ix_pins_text'), 'pins', ['text'], unique=False)
    op.drop_column('pins', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pins_text'), table_name='pins')
    op.create_index('ix_pins_description', 'pins', ['description'], unique=False)
    op.drop_column('pins', 'text')
    # ### end Alembic commands ###
