"""user

Revision ID: ab2c256ecf0d
Revises: 344ca20da8fb
Create Date: 2022-07-01 23:22:48.543511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2c256ecf0d'
down_revision = '344ca20da8fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
