"""text

Revision ID: ac2189ced8ee
Revises: 93f4f65b427e
Create Date: 2022-07-01 02:43:00.504289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2189ced8ee'
down_revision = '93f4f65b427e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
