"""first

Revision ID: ba8b5307cad2
Revises: 
Create Date: 2022-06-25 23:29:29.766963

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils as su


# revision identifiers, used by Alembic.
revision = 'ba8b5307cad2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pins_description'), 'pins', ['description'], unique=False)
    op.create_index(op.f('ix_pins_id'), 'pins', ['id'], unique=True)
    op.create_index(op.f('ix_pins_title'), 'pins', ['title'], unique=False)
    op.create_table('pin_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', su.URLType(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('pins_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pins_id'], ['pins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pin_images_id'), 'pin_images', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pin_images_id'), table_name='pin_images')
    op.drop_table('pin_images')
    op.drop_index(op.f('ix_pins_title'), table_name='pins')
    op.drop_index(op.f('ix_pins_id'), table_name='pins')
    op.drop_index(op.f('ix_pins_description'), table_name='pins')
    op.drop_table('pins')
    # ### end Alembic commands ###
